export LD_LIBRARY_PATH="/home/bihlmasn/miniconda3/lib:$LD_LIBRARY_PATH"
export LD_INCLUDE_PATH="/home/bihlmasn/miniconda3/include:$LD_INCLUDE_PATH"
export CUDA_HOME="/usr/local/cuda-11.2"
export PATH="/home/bihlmasn/miniconda3/bin:/usr/local/cuda-11.2/bin:$PATH"
export CPATH="/usr/local/cuda-11.2/include"
export CUDNN_INCLUDE_DIR="/usr/local/cuda-11.2/include"
export CUDNN_LIB_DIR="/usr/local/cuda-11.2/lib64"
